---
- hosts: DMZ_Automation_internal
  remote_user: jenkins
  become: yes
  become_user: root

  tasks:
    - name: add docker repo
      apt_repository:
        repo="deb https://download.docker.com/linux/ubuntu xenial stable"
        state=present
    - name: install repo gpg key
      apt_key:
        url="https://download.docker.com/linux/ubuntu/gpg"
        state=present
    - name: refresh cache and install docker-ce
      apt:
        name=docker-ce
        update_cache=yes
        state=latest
