- hosts: '{{ host }}'
  become: yes
  become_user: root
  tasks:
    - name: rename
      replace:
        path: /etc/default/grub
        regexp: GRUB_CMDLINE_LINUX=\"(.*)\"
        replace: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
        owner: root
        group: root
        mode: 0644

    - name: grub update
      shell: update-grub
